version: "3"

services:
 web:
  build: ./docker2
  image: docker.clkl.de/kinf/biogames:python2
  volumes:
   - ./biogames:/biogames
   - ../gamefield/:/gamefield
   - ./venv_web/:/venv/
   - ./gg-data/files/:/biogames/files/
   - ./gg-data/media/:/biogames/media/
  ports:
   - "5000:8000"
  restart: on-failure:5
  depends_on:
   - db

 celery:
  image: docker.clkl.de/kinf/biogames:python2
  volumes:
   - ./biogames:/biogames
   - ./venv_celery/:/venv/
   - ./gg-data/files/:/biogames/files/
   - ./gg-data/media/:/biogames/media/
  restart: on-failure:5
  command: ["celery", "worker"]
  depends_on:
   - db

 db:
  image: docker.clkl.de/postgis:9.6-alpine
  volumes:
   - ./postgres/:/var/lib/postgresql/data
  environment:
   - POSTGRES_PASSWORD=secret
  restart: on-failure:5
